[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "out"
libs = ["contracts/lib"]

fs_permissions = [{ access = "read", path = "contracts/test/fixtures" }]